### ISSUE TITLE
Combined Daily Data Provider Issues

### ISSUE THREAD

**Issue by ajmenca** [CareEvolution/MyDataHelpsUI#101]
- The combined daily data provider for RestingHeartRate checks data availability for AppleHealth, then Fitbit, then Garmin.  The `combinedRestingHeartRate` provider function, however, only actually queries for AppleHealth and Fitbit data.  If you were to use this for a participant that only had Garmin data, it wouldn't return valid data.

- Both the combined resting heart rate provider and the combined steps provider are not robust against a Project not having one of the data types enabled.  When a project doesn't have a data type enabled, the server returns a 500 error response; for the `simpleAvailabilityCheck` this is caught properly and returns false.  However the combined data providers don't know which providers are valid, and also do not `catch` errors from their data query, so they fail outright.  This means that if, for example, you enable Apple Health and Fitbit, but not Garmin, you can't actually use the Combined Steps aggregator (in this specific case you can use the combined RHR function because of the omission of the Garmin query noted above).

**Comment by ajmenca** [comment]
My second bullet point here was resolved in #112.

**Comment by brandoncharnesky** [comment]
First bullet point is resolved by:  https://github.com/CareEvolution/MyDataHelpsUI/pull/245
