### ISSUE TITLE
DeviceDataMonthChart Missing Translations

### ISSUE THREAD

**Issue by ajmenca** [CareEvolution/MyDataHelpsUI#221]
The "No Data" label and the "Daily Average" caption are both missing Spanish translation strings.

![image](https://github.com/CareEvolution/MyDataHelpsUI/assets/5473619/ca2b9205-18db-4ca4-bdf3-2e879a688cc2)
![image](https://github.com/CareEvolution/MyDataHelpsUI/assets/5473619/e4518b17-5a9a-4658-ac6d-69d1641ba8b4)

**Comment by brandoncharnesky** [comment]
Closed via https://github.com/CareEvolution/MyDataHelpsUI/pull/232
