### ISSUE TITLE
Bug: FitbitConnected Widget disappears when Fitbit is in "Needs Reconnection" State

### ISSUE THREAD

**Issue by Suvarna-Thejas-CE** [CareEvolution/MyDataHelpsUI#224]
I was using view builder to build a simple UI that allows you to connect Fitbit. 

This Fitbit Connect widget has a flag for "Hide when connected".

This widget remains hidden when the Fitbit Connection Status is "Needs Reconnection", so there is no way to reconnect the Fitbit account from the dashboard. 

i.e. .. this never shows up is "Hide when connected is checked off"
<img width="1126" alt="image" src="https://github.com/CareEvolution/MyDataHelpsUI/assets/60715340/70be93f6-7a79-4e84-88b6-a3c1286c2fe9">

**Comment by brandoncharnesky** [comment]
Fixed via https://github.com/CareEvolution/MyDataHelpsUI/pull/226 @Suvarna-Thejas-CE
