### ISSUE TITLE
Recharts Tooltips not working right

### ISSUE THREAD

**Issue by chrisnowak** [CareEvolution/MyDataHelpsUI#274]
In this PR I added overflow:visible to recharts-surface in order to ensure the axis ticks at the bottom weren't cut off
https://github.com/CareEvolution/MyDataHelpsUI/pull/268/files#diff-26dd15a660b7703f0b5fd2e30b004e2b39045e083d36e2e88e6ee86f18006725R76

However, it appears recharts does something where if a spot on the graph has no data, but that spot is selected due to the charts being "synced", it will just put the bar all the way to the left:
![Screenshot 2024-07-01 at 9 46 24 AM](https://github.com/CareEvolution/MyDataHelpsUI/assets/1643171/cd4c9ac0-b002-40bf-a00c-49662fb45f2b)

Reverting the overflow:visible change won't work entirely since it will still cut off certain axis labels, so we might need to fix the axis labels or hide the tooltip marker in this scenario probably

**Comment by chrisnowak** [comment]
Actually 🤦 I looked at that screenshot and it appears tooltips syncing is just off...as obviously the highlighted day there has data for all 3 graphs.  Looks like it might not be syncing properly:
![Screenshot 2024-07-01 at 9 51 02 AM](https://github.com/CareEvolution/MyDataHelpsUI/assets/1643171/5fe7af6f-0d09-4c71-b65a-8f8932b51199)

**Comment by ajmenca** [comment]
Curious - I just set up a story to try and reproduce this with the underlying TimeSeriesChart and it's working in the story.  I thought maybe the data gap in the Sleep Chart was somehow causing things to be offset incorrectly.  

![image](https://github.com/CareEvolution/MyDataHelpsUI/assets/5473619/0bf368c8-de5c-45fd-8604-24f0574cc1ea)

![image](https://github.com/CareEvolution/MyDataHelpsUI/assets/5473619/0b99b42d-2e78-4a5a-90ba-e29c9a9fd529)

![image](https://github.com/CareEvolution/MyDataHelpsUI/assets/5473619/5c83011c-e8b5-40b9-874e-6f7835d4b6cb)

**Comment by ajmenca** [comment]
Created a Story on the DailyDataChart too, which also seems to be working?

![image](https://github.com/CareEvolution/MyDataHelpsUI/assets/5473619/835b047c-2afa-4aa3-9874-5390dbcd7304)
