### ISSUE TITLE
Basic Points for Badges - Action after earning badge

### ISSUE THREAD

**Issue by reneefromhold** [CareEvolution/MyDataHelpsUI#326]
Add an action handler parameter to be used in place of awardBadgesViewURL

The existing parameter limits the behavior of what happens when a new badge is earned to a showing a whitelisted URL. Requiring a URL instead of a custom handler event forces the overhead of 1) creating a new view or sourcing one and 2) getting it whitelisted 

Associating actions or custom event handlers would also make the story more intuitive. In storybook we currently see up to a few second pause followed by a progress bar load to 100%, followed by a second pause, followed by the progress bar updating to show how many points are needed until the next badge is earned.

**Comment by chrisnowak** [comment]
@reneefromhold the current behavior is actually:
- progress bar loading 
- if it hits 100%, it launches the modal congratulating the user
- when the user returns to the screen, the progress bar would show points until next badge (so this "update" happens in the background)

But obviously showing the modal does not work in a story as it's MDH functionality

I think for 1.0 in view builder we should *not* ask the user to supply a url but rather we should have it launch the out of box view for awarding points

**Comment by reneefromhold** [comment]
Concern closed for vb 1.0
