### ISSUE TITLE
Combined daily data type availability checkers should use the data collection settings.

### ISSUE THREAD

**Issue by greinard** [CareEvolution/MyDataHelpsUI#366]
Currently, most/all combined daily data type availability checkers are not looking at the data collection settings to see if a given data source (such as Garmin) is enabled for the project.  This can result in a bunch of server side errors being logged even while under normal operating conditions.

For example, if you use a `DailyDataChart` with "combined steps", but don't have Garmin enabled for your project, because you are only interested in Apple Health and Fitbit step data, then you will cause errors to be logged every time it loads and the Garmin availability check runs.

I think the non-combined availability checkers are probably okay as is.  They could check the data collection settings as well, but I think it is less of an issue, because in the case of device specific data types, you probably wouldn't ever select them unless you also have them enabled for your project.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the combined daily data type availability checkers in the `src/helpers/daily-data-types/combined.tsx` file to check the data collection settings before performing availability checks for specific data sources. This change prevents unnecessary server-side errors when certain data sources are not enabled for the project.

You can review changes in this commit: https://github.com/jjyutm4532/CareEvolution-MyDataHelpsUI-366/commit/5268ecc8a15579ba9e550debaca3c0768e02e6a3.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
