### ISSUE TITLE
Correct spacing between "remember me" and checkbox for 2FA

### ISSUE THREAD

**Issue by basyl-durnan** [CareEvolution/MyDataHelpsUI#50]
There is no space between the checkbox and the "remember me" text when entering 2FA
![image](https://user-images.githubusercontent.com/88673856/235468818-31a0499d-abbd-41b2-9251-42576c31d1fd.png)

**Comment by chrisnowak** [comment]
@basyl-durnan wrong repository...would put this one in Consumers
